services:
  - type: web
    name: pulseanalysis
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn pulseanalysis.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"