# Generated by Django 5.2.10 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_healthmetrics_doctornote_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
