# Generated by Django 5.2.10 on 2026-03-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_patients', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_risk_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='suggested_disease',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='suggested_tests',
            field=models.TextField(blank=True),
        ),
    ]
