# Generated by Django 5.2.10 on 2026-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_assigned_doctor_patient_disease_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='activity_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='blood_oxygen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='data_source',
            field=models.CharField(default='Manual entry', max_length=30),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='sleep_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='stress_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='data_source',
            field=models.CharField(default='Manual entry', max_length=30),
        ),
        migrations.AddField(
            model_name='prediction',
            name='lifestyle_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='nervous_system_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='nervous_system_recovery_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='readable_ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='recommended_follow_up',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='risk_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='stress_sleep_insight',
            field=models.TextField(blank=True),
        ),
    ]
