# Generated by Django 5.2.10 on 2026-03-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_healthmetrics_activity_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("patient", "Patient"), ("doctor", "Doctor"), ("system", "System")],
                        default="patient",
                        max_length=20,
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=50)),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_interactions",
                        to="core.patient",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
