# Generated by Django 5.2.10 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_healthtrend_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtrend',
            name='is_synced',
            field=models.BooleanField(default=True, help_text='Whether this record is synced with cloud database'),
        ),
        migrations.AddField(
            model_name='healthtrend',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful cloud sync', null=True),
        ),
    ]
